Repository Agile-Arch-Angels/decentralized-tech-radar_dev, pull requests merged in 2024-05, with the labels that each got.

#46 refactor: use inteface to set the merging strategy
  docs/dev_docs/merger.md
  docs/dev_docs/merger_strategies.md
  src/Merger/Fcfs.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/cmd/merge.go
  src/go.mod
  src/go.sum
  test/integration_test.go
Labels: refactor

#55 feat: CLI can facilitate removing elements
  docs/user_docs/remove_usage.md
  src/cmd/remove.go
  test/end2end_test.go
Labels: feat

#59 chore: add a makefile to build project
  Makefile
Labels: chore

#58 feat: merge files with links to repos
  docs/dev_docs/merger.md
  src/Merger/Fcfs.go
  src/Merger/merger.go
  src/Merger/merger_test.go
Labels: feat

#60 ci: fix file extension for windows binary
  .github/workflows/build_test_release.yml
Labels: ci

#63 fix: fix issue where merge log didn't show picked file
  src/Merger/Fcfs.go
Labels: bug

#68 chore: update makefile to include HTML folder
  Makefile
Labels: chore

#66 ci: workflow example to generate radar
  .github/workflows/radar_workflow.yml
  ci/radar_build.go
  examples/workflows/ci/radar_build.go
  examples/workflows/github/radar_workflow.yml
  examples/workflows/workflows.md
Labels: ci
