Repository Agile-Arch-Angels/decentralized-tech-radar_dev, pull requests merged in 2024-04, with the labels that each got.

#13 feat: git fetcher with one repo and creates cache
  .github/workflows/build_test.yml
  .github/workflows/build_test_release.yml
  .gitignore
  examples/csv_templates/template.csv
  go.work.sum
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/main.go
Labels: feat

#16 chore: sync novo main with dev main
  ci/build_test_release.go
Labels: chore

#18 docs: add fetcher documentation
  docs/dev_docs/fetcher.md
  docs/user_docs/fetcher_usage.md
Labels: docs

#17 feat: duplicate deletion for Merger and Fetcher + basic CSV format verification
  .gitignore
  docs/dev_docs/verifier.md
  src/Fetcher/fetcher.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/Verifier/verifier.go
  src/Verifier/verifier_test.go
  src/cache/template.csv
  src/cache/template1.csv
  src/main.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#20 feat: integrate cobra with the --fetch flag/command
  docs/dev_docs/read_and_write.md
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/cmd/fetch.go
  src/cmd/root.go
  src/go.mod
  src/go.sum
  src/main.go
  test/end2end_test.go
Labels: feat

#22 feat: integrate cobra with the --cache flag/subcommand for merger
  docs/dev_docs/merger.md
  docs/user_docs/merger_usage.md
  src/Fetcher/fetcher.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/cmd/merge.go
  test/end2end_test.go
Labels: feat

#21 PR[4:1] feat: integrate cobra with the --generate flag/command
  docs/dev_docs/read_and_write.md
  docs/user_docs/generate_usage.md
  src/cmd/generate.go
Labels: feat

#24 test: Ensure working E2E test after cobra-integrations
  .gitignore
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/Merged_file.csv
  src/Verifier/verifier.go
  src/cmd/root.go
  test/end2end_test.go
  test/integration_test.go
Labels: test

#25 docs: docs quickstart user guide
  docs/images/quickstart_gifs/Fetching.gif
  docs/images/quickstart_gifs/Generate.gif
  docs/images/quickstart_gifs/Merging.gif
  docs/user_docs/quickstart.md
Labels: docs

#27 feat: chain command bashscript
  scripts/dev_scripts/cmd_chainer_dev.sh
Labels: feat

#30 refactor: split verifier function into two calls and ...
  src/Fetcher/fetcher.go
  src/Merger/merger.go
  src/Verifier/verifier.go
  src/Verifier/verifier_test.go
Labels: refactor

#28 refactor: fetcher branch & whitelist flags
  docs/user_docs/fetcher_usage.md
  src/cmd/fetch.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#33 chore: create .gitattributes and add linguist vendor ignore
  .gitattributes
Labels: chore

#34 refactore: ascii novo usage
  src/cmd/root.go
Labels: refactor

#35 chore: Change LICENSE to GAGPL 3.0
  LICENSE
Labels: chore

#36 chore: add credit to thoughtworks in readme
  README.md
Labels: chore

#37 Chore: add footer credit details in the html
  src/HTML/makeHtml.go
  src/js/stylesheets/style.css
Labels: chore

#39 refactor: progres bar now rounds to nearest 5% and is always 20 long
  src/Fetcher/fetcher.go
Labels: refactor

#38 feat: file of repos for fetching
  docs/user_docs/fetcher_usage.md
  src/cmd/fetch.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#41 ci: update dependabot to now include gomod
  .github/dependabot.yml
Labels: ci

#42 test: Add test for Merger's duplicationRemoval
  docs/dev_docs/merger.md
  src/Merger/merger.go
  src/Merger/merger_test.go
Labels: test

#40 Feat: finish backend of tech radar rendering
  src/HTML/css/style.css
  src/HTML/images/arrow-icon.svg
  src/HTML/images/arrow-white-icon.svg
  src/HTML/images/existing.svg
  src/HTML/images/favicon.ico
  src/HTML/images/first-quadrant-btn-bg.svg
  src/HTML/images/fourth-quadrant-btn-bg.svg
  src/HTML/images/logo.png
  src/HTML/images/new.svg
  src/HTML/images/pdf_banner.png
  src/HTML/images/radar_legend.png
  src/HTML/images/search-active-wave.svg
  src/HTML/images/search-logo-2x.svg
  src/HTML/images/second-quadrant-btn-bg.svg
  src/HTML/images/tech-radar-landing-page-wide.png
  src/HTML/images/third-quadrant-btn-bg.svg
  src/HTML/js/libraries/chance.js
  src/HTML/js/libraries/d3-collection.js
  src/HTML/js/libraries/d3-selection.js
  src/HTML/js/libraries/d3-tip.js
  src/HTML/js/libraries/d3.js
  src/HTML/js/libraries/jquery-ui.js
  src/HTML/js/libraries/jquery.js
  src/HTML/js/libraries/lodash.js
  src/HTML/js/libraries/require.js
  src/HTML/js/renderingTechRadar.js
  src/HTML/js/requireConfig.js
  src/HTML/makeHtml.go
  src/js/config.js
  src/js/graphing/blips.js
  src/js/graphing/components/banner.js
  src/js/graphing/components/buttons.js
  src/js/graphing/components/quadrantSubnav.js
  src/js/graphing/components/quadrantTables.js
  src/js/graphing/components/quadrants.js
  src/js/graphing/components/search.js
  src/js/graphing/config.js
  src/js/graphing/pdfPage.js
  src/js/graphing/radar.js
  src/js/images/favicon.ico
  src/js/models/blip.js
  src/js/models/quadrant.js
  src/js/models/radar.js
  src/js/models/ring.js
  src/js/requireConfig.js
  src/js/util/autoComplete.js
  src/js/util/factory.js
  src/js/util/htmlUtil.js
  src/js/util/inputSanitizer.js
  src/js/util/mathUtils.js
  src/js/util/queryParamProcessor.js
  src/js/util/ringCalculator.js
  src/js/util/stringUtil.js
  src/js/util/urlUtils.js
  src/specfile.csv
Labels: feat

#47 docs: add comments to funky code
  src/Merger/merger.go
  src/Verifier/verifier.go
Labels: docs

#50 bug: make quadrant names show
  src/HTML/js/renderingTechRadar.js
Labels: bug

#51 feat: CLI can facilitate adding elements...
  docs/user_docs/add_usage.md
  src/cmd/add.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#49 refactor: duplicate removal change to quadrants
  src/Merger/merger.go
Labels: refactor

#52 chore: add a go linter yaml file
  .golangci.yml
Labels: chore

#54 Style: create color palette for the rendering
  src/HTML/css/style.css
  src/HTML/images/existing.svg
  src/HTML/images/first-quadrant-btn-bg.svg
  src/HTML/images/fourth-quadrant-btn-bg.svg
  src/HTML/images/new.svg
  src/HTML/images/second-quadrant-btn-bg.svg
  src/HTML/images/third-quadrant-btn-bg.svg
  src/HTML/js/renderingTechRadar.js
  src/HTML/makeHtml.go
Labels: refactor

#53 feat: add url to fetched files
  docs/dev_docs/fetcher.md
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
Labels: feat
